Repository team-xquare/v1-service-git, pull requests merged in 2023-07, with the labels that each got.

#10 🔀 :: 깃랭크 SecurityConfig 수정
  git-infrastructure/src/main/kotlin/com/xquare/git/global/config/SecurityConfiguration.kt
Labels: chore

#11 🔀 :: 컬럼에 랭킹 추가
  git-application/src/main/kotlin/com/xquare/git/git/dto/FindAllUserResponse.kt
  git-application/src/main/kotlin/com/xquare/git/git/facade/GitFacade.kt
  git-application/src/main/kotlin/com/xquare/git/git/spi/QueryGitPort.kt
  git-application/src/main/kotlin/com/xquare/git/git/usecase/FindAllGitUseCase.kt
  git-application/src/main/kotlin/com/xquare/git/git/usecase/FindGitByCurrentUserIdUseCase.kt
  git-application/src/main/kotlin/com/xquare/git/git/usecase/SaveUsernameUseCase.kt
  git-application/src/main/kotlin/com/xquare/git/git/usecase/UpdateGitUseCase.kt
  git-domain/src/main/kotlin/com/xquare/git/git/model/Git.kt
  git-infrastructure/src/main/kotlin/com/xquare/git/persistence/git/mapper/GitMapper.kt
  git-infrastructure/src/main/kotlin/com/xquare/git/persistence/git/model/GitEntity.kt
  git-infrastructure/src/main/kotlin/com/xquare/git/persistence/git/spi/GitPersistenceAdapter.kt
  git-presentation/src/main/kotlin/com/xquare/git/GitHandler.kt
  git-presentation/src/main/kotlin/com/xquare/git/GitRouter.kt
Labels: 리팩토링

#12 🔀 :: Github Oauth 설정
  git-application/src/main/kotlin/com/xquare/git/git/exceptions/GitExceptions.kt
  git-application/src/main/kotlin/com/xquare/git/git/facade/GitFacade.kt
  git-application/src/main/kotlin/com/xquare/git/github/dto/GetGithubUserInfoResponse.kt
  git-application/src/main/kotlin/com/xquare/git/github/dto/TokenResponse.kt
  git-application/src/main/kotlin/com/xquare/git/github/spi/GithubPort.kt
  git-application/src/main/kotlin/com/xquare/git/github/spi/QueryGithubPort.kt
  git-application/src/main/kotlin/com/xquare/git/github/usecase/GetGithubAccessTokenUseCase.kt
  git-application/src/main/kotlin/com/xquare/git/github/usecase/GetGithubUserInfoUseCase.kt
  git-infrastructure/src/main/kotlin/com/xquare/git/persistence/github/spi/GithubPersistenceAdapter.kt
  git-presentation/src/main/kotlin/com/xquare/git/GitHandler.kt
Labels: 기능 추가

#14 🔀 :: (#206) 구조 변경 && 메소드, 변수명 리팩토링
  git-application/src/main/kotlin/com/xquare/v1servicegit/git/Git.kt
  git-application/src/main/kotlin/com/xquare/v1servicegit/git/dto/response/FindAllUserResponse.kt
  git-application/src/main/kotlin/com/xquare/v1servicegit/git/facade/GitFacade.kt
  git-application/src/main/kotlin/com/xquare/v1servicegit/git/usecase/FindAllGitUseCase.kt
  git-application/src/main/kotlin/com/xquare/v1servicegit/git/usecase/FindGitByCurrentUserIdUseCase.kt
  git-application/src/main/kotlin/com/xquare/v1servicegit/git/usecase/GitUseCase.kt
  git-application/src/main/kotlin/com/xquare/v1servicegit/git/usecase/SaveUsernameUseCase.kt
  git-application/src/main/kotlin/com/xquare/v1servicegit/git/usecase/UpdateGitUseCase.kt
  git-application/src/main/kotlin/com/xquare/v1servicegit/github/dto/response/GetGithubUserInfoResponse.kt
  git-application/src/main/kotlin/com/xquare/v1servicegit/github/dto/response/TokenResponse.kt
  git-application/src/main/kotlin/com/xquare/v1servicegit/github/port/QueryGithubPort.kt
  git-application/src/main/kotlin/com/xquare/v1servicegit/github/usecase/GetGithubAccessTokenUseCase.kt
  git-application/src/main/kotlin/com/xquare/v1servicegit/github/usecase/GetGithubUserInfoUseCase.kt
  git-application/src/main/kotlin/com/xquare/v1servicegit/user/dto/FindUserListResponse.kt
  git-application/src/main/kotlin/com/xquare/v1servicegit/user/dto/response/FindUserListResponse.kt
  git-application/src/main/kotlin/com/xquare/v1servicegit/user/port/QueryUserPort.kt
  git-infrastructure/src/main/kotlin/com/xquare/v1servicegit/common/config/SecurityConfiguration.kt
  git-infrastructure/src/main/kotlin/com/xquare/v1servicegit/git/GitPersistenceAdapter.kt
  git-infrastructure/src/main/kotlin/com/xquare/v1servicegit/git/router/GitHandler.kt
  git-infrastructure/src/main/kotlin/com/xquare/v1servicegit/git/router/GitRouter.kt
  git-infrastructure/src/main/kotlin/com/xquare/v1servicegit/github/GithubPersistenceAdapter.kt
  git-infrastructure/src/main/kotlin/com/xquare/v1servicegit/user/UserPersistenceAdapter.kt
Labels: chore, 리팩토링

#15 🔀 :: 테스트 코드 작성
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/DependencyVersions.kt
  git-application/build.gradle.kts
  git-application/src/test/kotlin/com/xquare/git/BaseApplicationTest.kt
  git-application/src/test/kotlin/com/xquare/git/config/DefaultTestConfig.kt
  git-application/src/test/kotlin/com/xquare/git/git/GitFixtures.kt
  git-application/src/test/kotlin/com/xquare/git/git/usecase/FindAllGitTest.kt
  git-application/src/test/kotlin/com/xquare/git/git/usecase/FindGitByCurrentUserIdTest.kt
  git-application/src/test/kotlin/com/xquare/git/git/usecase/SaveUsernameTest.kt
  git-application/src/test/kotlin/com/xquare/git/git/usecase/UpdateGitTest.kt
  git-application/src/test/kotlin/com/xquare/git/github/usecase/GetGithubAccessTokenTest.kt
  git-application/src/test/kotlin/com/xquare/git/github/usecase/GetGithubUserInfoTest.kt
Labels: 테스트 추가

#16 🔀 :: (#215) Github OAuth 연동됐는지 판별 여부 API 추가
  git-application/src/main/kotlin/com/xquare/v1servicegit/git/dto/response/IsConnectedGithubOauthResponse.kt
  git-application/src/main/kotlin/com/xquare/v1servicegit/git/port/QueryGitPort.kt
  git-application/src/main/kotlin/com/xquare/v1servicegit/git/usecase/GitUseCase.kt
  git-infrastructure/src/main/kotlin/com/xquare/v1servicegit/common/config/SecurityConfiguration.kt
  git-infrastructure/src/main/kotlin/com/xquare/v1servicegit/git/GitPersistenceAdapter.kt
  git-infrastructure/src/main/kotlin/com/xquare/v1servicegit/git/router/GitHandler.kt
  git-infrastructure/src/main/kotlin/com/xquare/v1servicegit/git/router/GitRouter.kt
Labels: 기능 추가, 리팩토링

#18 🔀 :: (#17) 랭킹 전체 조회 코드 정렬 수정
  git-application/src/main/kotlin/com/xquare/v1servicegit/git/usecase/GitUseCase.kt
Labels: chore
